{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "iti-kubernetes-challenge.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "iti-kubernetes-challenge.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "iti-kubernetes-challenge.selectorLabels" . | nindent 6 }}
{{- end }}

